#\u6570\u636E\u5E93
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wangyi?useSSL=false
    username: root
    password: 123456

#\u670D\u52A1\u5668\u8BBE\u7F6E
server:
  port: 8099
