spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.8.164.131:3306/wangyi?useSSL=false
    username: root
    password: root
server:
  port: 8080
